export const ADD_NEW_POINT: "ADD_NEW_POINT" = "ADD_NEW_POINT";
export const REMOVE_POINT: "REMOVE_POINT" = "REMOVE_POINT";
export const MOVE_POINT: "MOVE_POINT" = "MOVE_POINT";

export const CHANGE_MAP_CENTER: "CHANGE_MAP_CENTER" = "CHANGE_MAP_CENTER";
export const CHANGE_POINT_COORDINATES: "CHANGE_POINT_COORDINATES" =
  "CHANGE_POINT_COORDINATES";

export const START_LOADING: "START_LOADING" = "START_LOADING";
export const STOP_LOADING: "STOP_LOADING" = "STOP_LOADING";
export const SET_MESSAGE: "SET_MESSAGE" = "SET_MESSAGE";
export const SKIP_MESSAGE: "SKIP_MESSAGE" = "SKIP_MESSAGE";
